sudo: false
language: rust
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
    apt:
        packages:
            - libssl-dev

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    pushd .. && git clone https://github.com/xd009642/tarpaulin.git ct && cd ct && git checkout develop && cargo build && popd && 
    ../ct/target/debug/cargo-tarpaulin tarpaulin --ignore-tests --out Xml --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
