on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v1

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install rustfmt
        run: rustup component add rustfmt

      - name: rustfmt check
        run: cargo fmt --all -- --check

      - name: run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml

  test:
    name: test suite
    needs: [format]
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
        idtimeout-minutes: [30, 30, 30]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: test
        run: cargo test
