on: [pull_request]

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test
        run: cargo test
